# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('doc_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('pub_date', models.DateTimeField(verbose_name='publish on')),
                ('intro', models.CharField(max_length=500)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('markdown_content', models.CharField(max_length=5000)),
                ('how_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_types.HowTo')),
            ],
        ),
    ]
